name: budget_family
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^7.7.0
  dio: ^5.7.0
  dartz: ^0.10.1
  shared_preferences: ^2.3.2
  persistent_bottom_nav_bar_v2: ^5.3.0
  intl: ^0.19.0
  animated_snack_bar: ^0.4.0
  swipe_refresh: ^1.1.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  rxdart: ^0.28.0
  pie_chart: ^5.4.0
  fl_chart: ^0.69.0
  syncfusion_flutter_gauges: ^27.1.51
  syncfusion_flutter_charts: ^27.1.51


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0



# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
